require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe VarnishServersController do

  # This should return the minimal set of attributes required to create a valid
  # VarnishServer. As you add validations to VarnishServer, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end
  
  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # VarnishServersController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all varnish_servers as @varnish_servers" do
      varnish_server = VarnishServer.create! valid_attributes
      get :index, {}, valid_session
      assigns(:varnish_servers).should eq([varnish_server])
    end
  end

  describe "GET show" do
    it "assigns the requested varnish_server as @varnish_server" do
      varnish_server = VarnishServer.create! valid_attributes
      get :show, {:id => varnish_server.to_param}, valid_session
      assigns(:varnish_server).should eq(varnish_server)
    end
  end

  describe "GET new" do
    it "assigns a new varnish_server as @varnish_server" do
      get :new, {}, valid_session
      assigns(:varnish_server).should be_a_new(VarnishServer)
    end
  end

  describe "GET edit" do
    it "assigns the requested varnish_server as @varnish_server" do
      varnish_server = VarnishServer.create! valid_attributes
      get :edit, {:id => varnish_server.to_param}, valid_session
      assigns(:varnish_server).should eq(varnish_server)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new VarnishServer" do
        expect {
          post :create, {:varnish_server => valid_attributes}, valid_session
        }.to change(VarnishServer, :count).by(1)
      end

      it "assigns a newly created varnish_server as @varnish_server" do
        post :create, {:varnish_server => valid_attributes}, valid_session
        assigns(:varnish_server).should be_a(VarnishServer)
        assigns(:varnish_server).should be_persisted
      end

      it "redirects to the created varnish_server" do
        post :create, {:varnish_server => valid_attributes}, valid_session
        response.should redirect_to(VarnishServer.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved varnish_server as @varnish_server" do
        # Trigger the behavior that occurs when invalid params are submitted
        VarnishServer.any_instance.stub(:save).and_return(false)
        post :create, {:varnish_server => {}}, valid_session
        assigns(:varnish_server).should be_a_new(VarnishServer)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        VarnishServer.any_instance.stub(:save).and_return(false)
        post :create, {:varnish_server => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested varnish_server" do
        varnish_server = VarnishServer.create! valid_attributes
        # Assuming there are no other varnish_servers in the database, this
        # specifies that the VarnishServer created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        VarnishServer.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => varnish_server.to_param, :varnish_server => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested varnish_server as @varnish_server" do
        varnish_server = VarnishServer.create! valid_attributes
        put :update, {:id => varnish_server.to_param, :varnish_server => valid_attributes}, valid_session
        assigns(:varnish_server).should eq(varnish_server)
      end

      it "redirects to the varnish_server" do
        varnish_server = VarnishServer.create! valid_attributes
        put :update, {:id => varnish_server.to_param, :varnish_server => valid_attributes}, valid_session
        response.should redirect_to(varnish_server)
      end
    end

    describe "with invalid params" do
      it "assigns the varnish_server as @varnish_server" do
        varnish_server = VarnishServer.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        VarnishServer.any_instance.stub(:save).and_return(false)
        put :update, {:id => varnish_server.to_param, :varnish_server => {}}, valid_session
        assigns(:varnish_server).should eq(varnish_server)
      end

      it "re-renders the 'edit' template" do
        varnish_server = VarnishServer.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        VarnishServer.any_instance.stub(:save).and_return(false)
        put :update, {:id => varnish_server.to_param, :varnish_server => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested varnish_server" do
      varnish_server = VarnishServer.create! valid_attributes
      expect {
        delete :destroy, {:id => varnish_server.to_param}, valid_session
      }.to change(VarnishServer, :count).by(-1)
    end

    it "redirects to the varnish_servers list" do
      varnish_server = VarnishServer.create! valid_attributes
      delete :destroy, {:id => varnish_server.to_param}, valid_session
      response.should redirect_to(varnish_servers_url)
    end
  end

end
